package com.example.onlineenglish

import android.content.Context
import android.os.Bundle
import androidx.fragment.app.Fragment
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import android.widget.Toast
import com.example.onlineenglish.databinding.FragmentYanlisYapilanKelimelerBinding
import kotlin.random.Random

class YanlisYapilanKelimeler : Fragment() {

    private lateinit var tasarim:FragmentYanlisYapilanKelimelerBinding
    private lateinit var context: Context
    private lateinit var kelimeler:HashMap<String,String>
    override fun onCreateView(inflater: LayoutInflater, container: ViewGroup?, savedInstanceState: Bundle?): View? {
        tasarim = FragmentYanlisYapilanKelimelerBinding.inflate(inflater, container, false)
        kelimeler=HashMap<String,String>()
        context = requireContext()
        kelimekeyvalue()
        var kelimekey: String? = null
        var kelimevalue: String? = null
        var dogru=0
        var yanlis=0

        var vt = VeriTabaniYardimcisi(context)
        var rastgele = YanlisKelimelerDao().rastgeleKelimeGetir(vt)

        for (k in rastgele) {
            kelimekey = k.yanlis_kelime
            kelimevalue = kelimeler[kelimekey]
        }
        tasarim.kelimegetir.text=kelimekey.toString()

        tasarim.kontrol.setOnClickListener {
            if(tasarim.girdi.text.toString().toLowerCase().trim()==kelimevalue.toString().toLowerCase().trim()){
                Toast.makeText(context,"Doğru cevap :)",Toast.LENGTH_SHORT).show()
                dogru++
                tasarim.dogru.text="Doğru Sayısı: $dogru"
                rastgele=YanlisKelimelerDao().rastgeleKelimeGetir(vt)
                for(k in rastgele){
                    kelimekey=k.yanlis_kelime
                    kelimevalue=kelimeler[kelimekey]
                }
                tasarim.kelimegetir.text=kelimekey
            }else{
                Toast.makeText(context,"Doğru cevap $kelimevalue olacaktı :(",Toast.LENGTH_SHORT).show()
                yanlis++
                tasarim.yanlis.text="Yanlış Sayısı: $yanlis"
                rastgele=YanlisKelimelerDao().rastgeleKelimeGetir(vt)
                for(k in rastgele){
                    kelimekey=k.yanlis_kelime
                    kelimevalue=kelimeler[kelimekey]
                }
                tasarim.kelimegetir.text=kelimekey
            }
        }

        return tasarim.root
    }











    fun kelimekeyvalue(){
        kelimeler.put("Hello","Merhaba")
        kelimeler.put("Name","İsim")
        kelimeler.put("Town","Kasaba")
        kelimeler.put("Adventure", "Macera");
        kelimeler.put("Explore", "Keşfetmek");
        kelimeler.put("Tourism", "Turizm");
        kelimeler.put("Destination", "Hedef");
        kelimeler.put("Journey", "Yolculuk");
        kelimeler.put("Traveler", "Seyyah");
        kelimeler.put("Guide", "Rehber");
        kelimeler.put("Map", "Harita");
        kelimeler.put("Compass", "Pusula");
        kelimeler.put("Backpack", "Sırt çantası");
        kelimeler.put("Hotel", "Otel");
        kelimeler.put("Reservation", "Rezervasyon");
        kelimeler.put("Check-in", "Giriş yapmak");
        kelimeler.put("Check-out", "Çıkış yapmak");
        kelimeler.put("Room", "Oda");
        kelimeler.put("Suite", "Süit");
        kelimeler.put("Hostel", "Pansiyon");
        kelimeler.put("Camping", "Kamp yapma");
        kelimeler.put("Beach", "Plaj");
        kelimeler.put("Mountain", "Dağ");
        kelimeler.put("Forest", "Orman");
        kelimeler.put("Lake", "Göl");
        kelimeler.put("River", "Nehir");
        kelimeler.put("Island", "Ada");
        kelimeler.put("Ocean", "Okyanuz");
        kelimeler.put("Sunset", "Günbatımı");
        kelimeler.put("Sunrise", "Gündoğumu");
        kelimeler.put("Star", "Yıldız");
        kelimeler.put("Galaxy", "Galaksi");
        kelimeler.put("Universe", "Evren");
        kelimeler.put("Astronomy", "Astronomi");
        kelimeler.put("Telescope", "Teleskop");
        kelimeler.put("Planet", "Gezegen");
        kelimeler.put("Satellite", "Uydu");
        kelimeler.put("Constellation", "Takımyıldız");
        kelimeler.put("Science", "Bilim");
        kelimeler.put("Technology", "Teknoloji");
        kelimeler.put("Innovation", "İnovasyon");
        kelimeler.put("Research", "Araştırma");
        kelimeler.put("Discovery", "Keşif");
        kelimeler.put("Experiment", "Deney");
        kelimeler.put("Hypothesis", "Hipotez");
        kelimeler.put("Theory", "Teori");
        kelimeler.put("Law", "Yasa");
        kelimeler.put("Scientist", "Bilim adamı");
        kelimeler.put("Laboratory", "Laboratuvar");
        kelimeler.put("Chemistry", "Kimya");
        kelimeler.put("Physics", "Fizik");
        kelimeler.put("Biology", "Biyoloji");
        kelimeler.put("Mathematics", "Matematik");
        kelimeler.put("Geology", "Jeoloji");
        kelimeler.put("Environment", "Çevre");
        kelimeler.put("Ecology", "Ekoloji");
        kelimeler.put("Sustainability", "Sürdürülebilirlik");
        kelimeler.put("Conservation", "Koruma");
        kelimeler.put("Biodiversity", "Biyolojik çeşitlilik");
        kelimeler.put("Natural Resources", "Doğal kaynaklar");
        kelimeler.put("Climate Change", "İklim Değişikliği");
        kelimeler.put("Weather", "Hava Durumu");
        kelimeler.put("Climate", "İklim");
        kelimeler.put("Temperature", "Sıcaklık");
        kelimeler.put("Rainfall", "Yağış");
        kelimeler.put("Snowfall", "Kar yağışı");
        kelimeler.put("Wind Speed", "Rüzgar hızı");
        kelimeler.put("Hurricane", "Kasırga");
        kelimeler.put("Earthquake", "Deprem");
        kelimeler.put("Tornado", "Tornado");
        kelimeler.put("Flood", "Sel");
        kelimeler.put("Fire", "Yangın");
        kelimeler.put("Emergency", "Acil durum");
        kelimeler.put("First Aid", "İlk yardım");
        kelimeler.put("Safety", "Güvenlik");
        kelimeler.put("Prevention", "Önleme");
        kelimeler.put("Awareness", "Farkındalık");
        kelimeler.put("Community", "Topluluk");
        kelimeler.put("Volunteer", "Gönüllü");
        kelimeler.put("Donation", "Bağış");
        kelimeler.put("Charity", "Hayır kurumu");
        kelimeler.put("Philanthropy", "Felsefe");
        kelimeler.put("Culture", "Kültür");
        kelimeler.put("Tradition", "Gelenek");
        kelimeler.put("Custom", "Adet");
        kelimeler.put("Language", "Dil");
        kelimeler.put("Communication", "İletişim");
        kelimeler.put("Media", "Medya");
        kelimeler.put("Newspaper", "Gazete");
        kelimeler.put("Magazine", "Dergi");
        kelimeler.put("Radio", "Radyo");
        kelimeler.put("Television", "Televizyon");
        kelimeler.put("Internet", "İnternet");
        kelimeler.put("Social Media", "Sosyal Medya");
        kelimeler.put("Journalism", "Gazetecilik");
        kelimeler.put("Reporter", "Muhabir");
        kelimeler.put("Editor", "Editör");
        kelimeler.put("News", "Haberler");
        kelimeler.put("Headline", "Manşet");
        kelimeler.put("Interview", "Röportaj");
        kelimeler.put("Article", "Makale");
        kelimeler.put("Opinion", "Görüş");
        kelimeler.put("Analysis", "Analiz");
        kelimeler.put("Entertainment", "Eğlence");
        kelimeler.put("Music", "Müzik");
        kelimeler.put("Film", "Film");
        kelimeler.put("Theatre", "Tiyatro");
        kelimeler.put("Map", "Harita");
        kelimeler.put("Holiday", "Tatil");
        kelimeler.put("Vacation", "İzin");
        kelimeler.put("Adventure", "Macera");
        kelimeler.put("Explore", "Keşfetmek");
        kelimeler.put("Tourism", "Turizm");
        kelimeler.put("Destination", "Hedef");
        kelimeler.put("Journey", "Yolculuk");
        kelimeler.put("Traveler", "Seyyah");
        kelimeler.put("Guide", "Rehber");
        kelimeler.put("Map", "Harita");
        kelimeler.put("Compass", "Pusula");
        kelimeler.put("Backpack", "Sırt çantası");
        kelimeler.put("Hotel", "Otel");
        kelimeler.put("Reservation", "Rezervasyon");
        kelimeler.put("Check-in", "Giriş yapmak");
        kelimeler.put("Check-out", "Çıkış yapmak");
        kelimeler.put("Room", "Oda");
        kelimeler.put("Suite", "Süit");
        kelimeler.put("Hostel", "Pansiyon");
        kelimeler.put("Camping", "Kamp yapma");
        kelimeler.put("Beach", "Plaj");
        kelimeler.put("Mountain", "Dağ");
        kelimeler.put("Forest", "Orman");
        kelimeler.put("Lake", "Göl");
        kelimeler.put("River", "Nehir");
        kelimeler.put("Island", "Ada");
        kelimeler.put("Ocean", "Okyanuz");
        kelimeler.put("Sunset", "Günbatımı");
        kelimeler.put("Sunrise", "Gündoğumu");
        kelimeler.put("Star", "Yıldız");
        kelimeler.put("Galaxy", "Galaksi");
        kelimeler.put("Universe", "Evren");
        kelimeler.put("Astronomy", "Astronomi");
        kelimeler.put("Telescope", "Teleskop");
        kelimeler.put("Planet", "Gezegen");
        kelimeler.put("Satellite", "Uydu");
        kelimeler.put("Constellation", "Takımyıldız");
        kelimeler.put("Science", "Bilim");
        kelimeler.put("Technology", "Teknoloji");
        kelimeler.put("Innovation", "İnovasyon");
        kelimeler.put("Research", "Araştırma");
        kelimeler.put("Discovery", "Keşif");
        kelimeler.put("Experiment", "Deney");
        kelimeler.put("Hypothesis", "Hipotez");
        kelimeler.put("Theory", "Teori");
        kelimeler.put("Law", "Yasa");
        kelimeler.put("Scientist", "Bilim adamı");
        kelimeler.put("Laboratory", "Laboratuvar");
        kelimeler.put("Chemistry", "Kimya");
        kelimeler.put("Physics", "Fizik");
        kelimeler.put("Biology", "Biyoloji");
        kelimeler.put("Mathematics", "Matematik");
        kelimeler.put("Geology", "Jeoloji");
        kelimeler.put("Environment", "Çevre");
        kelimeler.put("Ecology", "Ekoloji");
        kelimeler.put("Sustainability", "Sürdürülebilirlik");
        kelimeler.put("Conservation", "Koruma");
        kelimeler.put("Biodiversity", "Biyolojik çeşitlilik");
        kelimeler.put("Natural Resources", "Doğal kaynaklar");
        kelimeler.put("Climate Change", "İklim Değişikliği");
        kelimeler.put("Weather", "Hava Durumu");
        kelimeler.put("Climate", "İklim");
        kelimeler.put("Temperature", "Sıcaklık");
        kelimeler.put("Rainfall", "Yağış");
        kelimeler.put("Snowfall", "Kar yağışı");
        kelimeler.put("Wind Speed", "Rüzgar hızı");
        kelimeler.put("Hurricane", "Kasırga");
        kelimeler.put("Earthquake", "Deprem");
        kelimeler.put("Tornado", "Tornado");
        kelimeler.put("Flood", "Sel");
        kelimeler.put("Fire", "Yangın");
        kelimeler.put("Emergency", "Acil durum");
        kelimeler.put("First Aid", "İlk yardım");
        kelimeler.put("Safety", "Güvenlik");
        kelimeler.put("Prevention", "Önleme");
        kelimeler.put("Awareness", "Farkındalık");
        kelimeler.put("Community", "Topluluk");
        kelimeler.put("Volunteer", "Gönüllü");
        kelimeler.put("Donation", "Bağış");
        kelimeler.put("Charity", "Hayır kurumu");
        kelimeler.put("Philanthropy", "Felsefe");
        kelimeler.put("Culture", "Kültür");
        kelimeler.put("Tradition", "Gelenek");
        kelimeler.put("Custom", "Adet");
        kelimeler.put("Language", "Dil");
        kelimeler.put("Communication", "İletişim");
        kelimeler.put("Media", "Medya");
        kelimeler.put("Newspaper", "Gazete");
        kelimeler.put("Magazine", "Dergi");
        kelimeler.put("Radio", "Radyo");
        kelimeler.put("Television", "Televizyon");
        kelimeler.put("Internet", "İnternet");
        kelimeler.put("Social Media", "Sosyal Medya");
        kelimeler.put("Journalism", "Gazetecilik");
        kelimeler.put("Reporter", "Muhabir");
        kelimeler.put("Editor", "Editör");
        kelimeler.put("News", "Haberler");
        kelimeler.put("Headline", "Manşet");
        kelimeler.put("Interview", "Röportaj");
        kelimeler.put("Article", "Makale");
        kelimeler.put("Opinion", "Görüş");
        kelimeler.put("Analysis", "Analiz");
        kelimeler.put("Entertainment", "Eğlence");
        kelimeler.put("Music", "Müzik");
        kelimeler.put("Film", "Film");
        kelimeler.put("Theatre", "Tiyatro");
        kelimeler.put("Art", "Sanat");
        kelimeler.put("Literature", "Edebiyat");
        kelimeler.put("Performance", "Performans");
        kelimeler.put("Concert", "Konser");
        kelimeler.put("Festival", "Festival");
        kelimeler.put("Celebration", "Kutlama");
        kelimeler.put("Party", "Parti");
        kelimeler.put("Dance", "Dans");
        kelimeler.put("Fashion", "Moda");
        kelimeler.put("Design", "Tasarım");
        kelimeler.put("Style", "Stil");
        kelimeler.put("Trend", "Trend");
        kelimeler.put("Beauty", "Güzellik");
        kelimeler.put("Health", "Sağlık");
        kelimeler.put("Wellness", "Sağlıklı yaşam");
        kelimeler.put("Fitness", "Fitness");
        kelimeler.put("Exercise", "Egzersiz");
        kelimeler.put("Nutrition", "Beslenme");
        kelimeler.put("Diet", "Diyet");
        kelimeler.put("Mental Health", "Mental sağlık");
        kelimeler.put("Stress", "Stres");
        kelimeler.put("Relaxation", "Rahatlama");
        kelimeler.put("Mindfulness", "Farkındalık");
        kelimeler.put("Hobby", "Hobi");
        kelimeler.put("Art", "Sanat");
        kelimeler.put("Craft", "El sanatı");
        kelimeler.put("Music", "Müzik");
        kelimeler.put("Reading", "Okuma");
        kelimeler.put("Writing", "Yazma");
        kelimeler.put("Photography", "Fotoğrafçılık");
        kelimeler.put("Travel", "Seyahat");
        kelimeler.put("Gardening", "Bahçe işleri");
        kelimeler.put("Cooking", "Pişirme");
        kelimeler.put("Sports", "Spor");
        kelimeler.put("Football", "Futbol");
        kelimeler.put("Basketball", "Basketbol");
        kelimeler.put("Tennis", "Tenis");
        kelimeler.put("Swimming", "Yüzme");
        kelimeler.put("Cycling", "Bisiklet");
        kelimeler.put("Running", "Koşu");
        kelimeler.put("Nature", "Doğa");
        kelimeler.put("Environment", "Çevre");
        kelimeler.put("Climate", "İklim");
        kelimeler.put("Green", "Yeşil");
        kelimeler.put("Animal", "Hayvan");
        kelimeler.put("Plant", "Bitki");
        kelimeler.put("Tree", "Ağaç");
        kelimeler.put("Flower", "Çiçek");
        kelimeler.put("Bird", "Kuş");
        kelimeler.put("Insect", "Böcek");
        kelimeler.put("Fish", "Balık");
        kelimeler.put("Reptile", "Sürüngen");
        kelimeler.put("Amphibian", "Amfibi");
        kelimeler.put("Mammal", "Memeli");
        kelimeler.put("Human", "İnsan");
        kelimeler.put("Society", "Toplum");
        kelimeler.put("Culture", "Kültür");
        kelimeler.put("Tradition", "Gelenek");
        kelimeler.put("Custom", "Adet");
        kelimeler.put("Language", "Dil");
        kelimeler.put("Communication", "İletişim");
        kelimeler.put("Relationship", "İlişki");
        kelimeler.put("Friendship", "Dostluk");
        kelimeler.put("Love", "Aşk");
        kelimeler.put("Marriage", "Evlilik");
        kelimeler.put("Family", "Aile");
        kelimeler.put("Parent", "Ebeveyn");
        kelimeler.put("Child", "Çocuk");
        kelimeler.put("Sibling", "Kardeş");
        kelimeler.put("Relative", "Akraba");
        kelimeler.put("Friend", "Arkadaş");
        kelimeler.put("Neighbour", "Komşu");
        kelimeler.put("Community", "Topluluk");
        kelimeler.put("City", "Şehir");
        kelimeler.put("Village", "Köy");
        kelimeler.put("Town", "Kasaba");
        kelimeler.put("Building", "Bina");
        kelimeler.put("House", "Ev");
        kelimeler.put("Apartment", "Apartman");
        kelimeler.put("Room", "Oda");
        kelimeler.put("Furniture", "Mobilya");
        kelimeler.put("Bed", "Yatak");
        kelimeler.put("Sofa", "Kanepe");
        kelimeler.put("Table", "Masa");
        kelimeler.put("Chair", "Sandalye");
        kelimeler.put("Closet", "Dolap");
        kelimeler.put("Electronics", "Elektronik");
        kelimeler.put("Computer", "Bilgisayar");
        kelimeler.put("Laptop", "Dizüstü bilgisayar");
        kelimeler.put("Tablet", "Tablet");
        kelimeler.put("Smartphone", "Akıllı telefon");
        kelimeler.put("Television", "Televizyon");
        kelimeler.put("Camera", "Kamera");
        kelimeler.put("Headphones", "Kulaklık");
        kelimeler.put("Speaker", "Hoparlör");
        kelimeler.put("Internet", "İnternet");
        kelimeler.put("Website", "Web sitesi");
        kelimeler.put("Social Media", "Sosyal Medya");
        kelimeler.put("Email", "E-posta");
        kelimeler.put("Message", "Mesaj");
        kelimeler.put("Call", "Arama");
        kelimeler.put("Video Call", "Video arama");
        kelimeler.put("Chat", "Sohbet");
        kelimeler.put("Emoticon", "Emotikon");
        kelimeler.put("Emoji", "Emoji");
        kelimeler.put("Profile", "Profil");
        kelimeler.put("Username", "Kullanıcı adı");
        kelimeler.put("Password", "Parola");
        kelimeler.put("Security", "Güvenlik");
        kelimeler.put("Privacy", "Gizlilik");
        kelimeler.put("Settings", "Ayarlar");
        kelimeler.put("Notification", "Bildirim");
        kelimeler.put("App", "Uygulama");
        kelimeler.put("Download", "İndirme");
        kelimeler.put("Upload", "Yükleme");
        kelimeler.put("File", "Dosya");
        kelimeler.put("Folder", "Klasör");
        kelimeler.put("Document", "Belge");
        kelimeler.put("Presentation", "Sunum");
        kelimeler.put("Spreadsheet", "Elektronik tablo");
        kelimeler.put("Database", "Veritabanı");
        kelimeler.put("Programming", "Programlama");
        kelimeler.put("Code", "Kod");
        kelimeler.put("Developer", "Geliştirici");
        kelimeler.put("Bug", "Hata");
        kelimeler.put("Debugging", "Hata ayıklama");
        kelimeler.put("Version", "Sürüm");
        kelimeler.put("Update", "Güncelleme");
        kelimeler.put("Release", "Yayımlama");
        kelimeler.put("Open Source", "Açık kaynak");
        kelimeler.put("License", "Lisans");
        kelimeler.put("Community", "Topluluk");
        kelimeler.put("Collaboration", "İşbirliği");
        kelimeler.put("Project", "Proje");
        kelimeler.put("Deadline", "Son tarih");
        kelimeler.put("Meeting", "Toplantı");
        kelimeler.put("Team", "Ekip");
        kelimeler.put("Manager", "Yönetici");
        kelimeler.put("Colleague", "İş arkadaşı");
        kelimeler.put("Office", "Ofis");
        kelimeler.put("Remote", "Uzaktan");
        kelimeler.put("Work", "Çalışma");
        kelimeler.put("Job", "İş");
        kelimeler.put("Career", "Kariyer");
        kelimeler.put("Success", "Başarı");
        kelimeler.put("Failure", "Başarısızlık");
        kelimeler.put("Motivation", "Motivasyon");
        kelimeler.put("Goal", "Hedef");
        kelimeler.put("Productivity", "Üretkenlik");
        kelimeler.put("Efficiency", "Verimlilik");
        kelimeler.put("Quality", "Kalite");
        kelimeler.put("Customer", "Müşteri");
        kelimeler.put("Service", "Hizmet");
        kelimeler.put("Experience", "Deneyim");
        kelimeler.put("Satisfaction", "Memnuniyet");
        kelimeler.put("Feedback", "Geribildirim");
        kelimeler.put("Complaint", "Şikayet");
        kelimeler.put("Resolution", "Çözüm");
        kelimeler.put("Innovation", "Yenilik");
        kelimeler.put("Creativity", "Yaratıcılık");
        kelimeler.put("Imagination", "Hayal gücü");
        kelimeler.put("Inspiration", "İlham");
        kelimeler.put("Art", "Sanat");
        kelimeler.put("Music", "Müzik");
        kelimeler.put("Literature", "Edebiyat");
        kelimeler.put("Film", "Film");
        kelimeler.put("Theatre", "Tiyatro");
        kelimeler.put("Dance", "Dans");
        kelimeler.put("Visual Arts", "Görsel Sanatlar");
        kelimeler.put("Craft", "El sanatı");
        kelimeler.put("Design", "Tasarım");
        kelimeler.put("Fashion", "Moda");
        kelimeler.put("Architecture", "Mimarlık");
        kelimeler.put("Photography", "Fotoğrafçılık");
        kelimeler.put("Cuisine", "Mutfak");
        kelimeler.put("Culinary", "Mutfak sanatları");
        kelimeler.put("Food", "Yemek");
        kelimeler.put("Cooking", "Pişirme");
        kelimeler.put("Baking", "Fırınlama");
        kelimeler.put("Ingredient", "Malzeme");
        kelimeler.put("Recipe", "Tarif");
        kelimeler.put("Flavor", "Lezzet");
        kelimeler.put("Taste", "Tat");
        kelimeler.put("Spice", "Baharat");
        kelimeler.put("Herb", "Bitki");
        kelimeler.put("Beverage", "İçecek");
        kelimeler.put("Wine", "Şarap");
        kelimeler.put("Beer", "Bira");
        kelimeler.put("Coffee", "Kahve");
        kelimeler.put("Tea", "Çay");
        kelimeler.put("Cocktail", "Kokteyl");
        kelimeler.put("Juice", "Meyve suyu");
        kelimeler.put("Soft Drink", "Gazlı içecek");
        kelimeler.put("Water", "Su");
        kelimeler.put("Soda", "Soda");
        kelimeler.put("Health", "Sağlık");
        kelimeler.put("Wellness", "Sağlıklı yaşam");
        kelimeler.put("Fitness", "Fitness");
        kelimeler.put("Exercise", "Egzersiz");
        kelimeler.put("Nutrition", "Beslenme");
        kelimeler.put("Diet", "Diyet");
        kelimeler.put("Mental Health", "Mental sağlık");
        kelimeler.put("Stress", "Stres");
        kelimeler.put("Relaxation", "Rahatlama");
        kelimeler.put("Mindfulness", "Farkındalık");
        kelimeler.put("Social", "Sosyal");
        kelimeler.put("Relationship", "İlişki");
        kelimeler.put("Friendship", "Dostluk");
        kelimeler.put("Love", "Aşk");
        kelimeler.put("Marriage", "Evlilik");
        kelimeler.put("Family", "Aile");
        kelimeler.put("Parent", "Ebeveyn");
        kelimeler.put("Child", "Çocuk");
        kelimeler.put("Sibling", "Kardeş");
        kelimeler.put("Relative", "Akraba");
        kelimeler.put("Friend", "Arkadaş");
        kelimeler.put("Neighbour", "Komşu");
        kelimeler.put("Community", "Topluluk");
        kelimeler.put("City", "Şehir");
        kelimeler.put("Village", "Köy");
        kelimeler.put("Town", "Kasaba");
        kelimeler.put("Holiday", "Tatil");
        kelimeler.put("Vacation", "İzin");
        kelimeler.put("Adventure", "Macera");
        kelimeler.put("Explore", "Keşfetmek");
        kelimeler.put("Tourism", "Turizm");
        kelimeler.put("Destination", "Hedef");
        kelimeler.put("Journey", "Yolculuk");
        kelimeler.put("Traveler", "Seyyah");
        kelimeler.put("Guide", "Rehber");
        kelimeler.put("Map", "Harita");
        kelimeler.put("Compass", "Pusula");
        kelimeler.put("Backpack", "Sırt çantası");
        kelimeler.put("Hotel", "Otel");
        kelimeler.put("Reservation", "Rezervasyon");
        kelimeler.put("Check-in", "Giriş yapmak");
        kelimeler.put("Check-out", "Çıkış yapmak");
        kelimeler.put("Room", "Oda");
        kelimeler.put("Suite", "Süit");
        kelimeler.put("Hostel", "Pansiyon");
        kelimeler.put("Camping", "Kamp yapma");
        kelimeler.put("Beach", "Plaj");
        kelimeler.put("Mountain", "Dağ");
        kelimeler.put("Forest", "Orman");
        kelimeler.put("Lake", "Göl");
        kelimeler.put("River", "Nehir");
        kelimeler.put("Island", "Ada");
        kelimeler.put("Ocean", "Okyanuz");
        kelimeler.put("Sunset", "Günbatımı");
        kelimeler.put("Sunrise", "Gündoğumu");
        kelimeler.put("Star", "Yıldız");
        kelimeler.put("Galaxy", "Galaksi");
        kelimeler.put("Universe", "Evren");
        kelimeler.put("Astronomy", "Astronomi");
        kelimeler.put("Telescope", "Teleskop");
        kelimeler.put("Planet", "Gezegen");
        kelimeler.put("Satellite", "Uydu");
        kelimeler.put("Constellation", "Takımyıldız");
        kelimeler.put("Science", "Bilim");
        kelimeler.put("Technology", "Teknoloji");
        kelimeler.put("Innovation", "İnovasyon");
        kelimeler.put("Research", "Araştırma");
        kelimeler.put("Discovery", "Keşif");
        kelimeler.put("Experiment", "Deney");
        kelimeler.put("Hypothesis", "Hipotez");
        kelimeler.put("Theory", "Teori");
        kelimeler.put("Law", "Yasa");
        kelimeler.put("Scientist", "Bilim adamı");
        kelimeler.put("Laboratory", "Laboratuvar");
        kelimeler.put("Chemistry", "Kimya");
        kelimeler.put("Physics", "Fizik");
        kelimeler.put("Biology", "Biyoloji");
        kelimeler.put("Mathematics", "Matematik");
        kelimeler.put("Geology", "Jeoloji");
        kelimeler.put("Environment", "Çevre");
        kelimeler.put("Ecology", "Ekoloji");
        kelimeler.put("Sustainability", "Sürdürülebilirlik");
        kelimeler.put("Conservation", "Koruma");
        kelimeler.put("Biodiversity", "Biyolojik çeşitlilik");
        kelimeler.put("Natural Resources", "Doğal kaynaklar");
        kelimeler.put("Climate Change", "İklim Değişikliği");
        kelimeler.put("Weather", "Hava Durumu");
        kelimeler.put("Climate", "İklim");
        kelimeler.put("Temperature", "Sıcaklık");
        kelimeler.put("Rainfall", "Yağış");
        kelimeler.put("Snowfall", "Kar yağışı");
        kelimeler.put("Wind Speed", "Rüzgar hızı");
        kelimeler.put("Hurricane", "Kasırga");
        kelimeler.put("Earthquake", "Deprem");
        kelimeler.put("Tornado", "Tornado");
        kelimeler.put("Flood", "Sel");
        kelimeler.put("Fire", "Yangın");
        kelimeler.put("Emergency", "Acil durum");
        kelimeler.put("First Aid", "İlk yardım");
        kelimeler.put("Safety", "Güvenlik");
        kelimeler.put("Prevention", "Önleme");
        kelimeler.put("Awareness", "Farkındalık");
        kelimeler.put("Community", "Topluluk");
        kelimeler.put("Volunteer", "Gönüllü");
        kelimeler.put("Donation", "Bağış");
        kelimeler.put("Charity", "Hayır kurumu");
        kelimeler.put("Philanthropy", "Felsefe");
        kelimeler.put("Culture", "Kültür");
        kelimeler.put("Tradition", "Gelenek");
        kelimeler.put("Custom", "Adet");
        kelimeler.put("Language", "Dil");
        kelimeler.put("Communication", "İletişim");
        kelimeler.put("Media", "Medya");
        kelimeler.put("Newspaper", "Gazete");
        kelimeler.put("Magazine", "Dergi");
        kelimeler.put("Radio", "Radyo");
        kelimeler.put("Television", "Televizyon");
        kelimeler.put("Internet", "İnternet");
        kelimeler.put("Social Media", "Sosyal Medya");
        kelimeler.put("Journalism", "Gazetecilik");
        kelimeler.put("Reporter", "Muhabir");
        kelimeler.put("Editor", "Editör");
        kelimeler.put("News", "Haberler");
        kelimeler.put("Headline", "Manşet");
        kelimeler.put("Interview", "Röportaj");
        kelimeler.put("Article", "Makale");
        kelimeler.put("Opinion", "Görüş");
        kelimeler.put("Analysis", "Analiz");
        kelimeler.put("Entertainment", "Eğlence");
        kelimeler.put("Music", "Müzik");
        kelimeler.put("Film", "Film");
        kelimeler.put("Theatre", "Tiyatro");
        kelimeler.put("Art", "Sanat");
        kelimeler.put("Literature", "Edebiyat");
        kelimeler.put("Performance", "Performans");
        kelimeler.put("Concert", "Konser");
        kelimeler.put("Festival", "Festival");
        kelimeler.put("Celebration", "Kutlama");
        kelimeler.put("Party", "Parti");
        kelimeler.put("Dance", "Dans");
        kelimeler.put("Fashion", "Moda");
        kelimeler.put("Design", "Tasarım");
        kelimeler.put("Style", "Stil");
        kelimeler.put("Trend", "Trend");
        kelimeler.put("Beauty", "Güzellik");
        kelimeler.put("Health", "Sağlık");
        kelimeler.put("Wellness", "Sağlıklı yaşam");
        kelimeler.put("Fitness", "Fitness");
        kelimeler.put("Exercise", "Egzersiz");
        kelimeler.put("Nutrition", "Beslenme");
        kelimeler.put("Diet", "Diyet");
        kelimeler.put("Mental Health", "Mental sağlık");
        kelimeler.put("Stress", "Stres");
        kelimeler.put("Relaxation", "Rahatlama");
        kelimeler.put("Mindfulness", "Farkındalık");
        kelimeler.put("Hobby", "Hobi");
        kelimeler.put("Art", "Sanat");
        kelimeler.put("Craft", "El sanatı");
        kelimeler.put("Music", "Müzik");
        kelimeler.put("Reading", "Okuma");
        kelimeler.put("Writing", "Yazma");
        kelimeler.put("Photography", "Fotoğrafçılık");
        kelimeler.put("Travel", "Seyahat");
        kelimeler.put("Gardening", "Bahçe işleri");
        kelimeler.put("Cooking", "Pişirme");
        kelimeler.put("Sports", "Spor");
        kelimeler.put("Football", "Futbol");
        kelimeler.put("Basketball", "Basketbol");
        kelimeler.put("Tennis", "Tenis");
        kelimeler.put("Swimming", "Yüzme");
        kelimeler.put("Cycling", "Bisiklet");
        kelimeler.put("Running", "Koşu");
        kelimeler.put("Nature", "Doğa");
        kelimeler.put("Environment", "Çevre");
        kelimeler.put("Climate", "İklim");
        kelimeler.put("Green", "Yeşil");
        kelimeler.put("Animal", "Hayvan");
        kelimeler.put("Plant", "Bitki");
        kelimeler.put("Tree", "Ağaç");
        kelimeler.put("Flower", "Çiçek");
        kelimeler.put("Bird", "Kuş");
        kelimeler.put("Insect", "Böcek");
        kelimeler.put("Fish", "Balık");
        kelimeler.put("Reptile", "Sürüngen");
        kelimeler.put("Amphibian", "Amfibi");
        kelimeler.put("Mammal", "Memeli");
        kelimeler.put("Human", "İnsan");
        kelimeler.put("Society", "Toplum");
        kelimeler.put("Culture", "Kültür");
        kelimeler.put("Tradition", "Gelenek");
        kelimeler.put("Custom", "Adet");
        kelimeler.put("Language", "Dil");
        kelimeler.put("Communication", "İletişim");
        kelimeler.put("Relationship", "İlişki");
        kelimeler.put("Friendship", "Dostluk");
        kelimeler.put("Love", "Aşk");
        kelimeler.put("Marriage", "Evlilik");
        kelimeler.put("Family", "Aile");
        kelimeler.put("Parent", "Ebeveyn");
        kelimeler.put("Child", "Çocuk");
        kelimeler.put("Sibling", "Kardeş");
        kelimeler.put("Relative", "Akraba");
        kelimeler.put("Friend", "Arkadaş");
        kelimeler.put("Neighbour", "Komşu");
        kelimeler.put("Community", "Topluluk");
        kelimeler.put("City", "Şehir");
        kelimeler.put("Village", "Köy");
        kelimeler.put("Town", "Kasaba");
        kelimeler.put("Building", "Bina");
        kelimeler.put("House", "Ev");
        kelimeler.put("Apartment", "Apartman");
        kelimeler.put("Room", "Oda");
        kelimeler.put("Furniture", "Mobilya");
        kelimeler.put("Bed", "Yatak");
        kelimeler.put("Sofa", "Kanepe");
        kelimeler.put("Table", "Masa");
        kelimeler.put("Chair", "Sandalye");
        kelimeler.put("Closet", "Dolap");
        kelimeler.put("Electronics", "Elektronik");
        kelimeler.put("Computer", "Bilgisayar");
        kelimeler.put("Laptop", "Dizüstü bilgisayar");
        kelimeler.put("Tablet", "Tablet");
        kelimeler.put("Smartphone", "Akıllı telefon");
        kelimeler.put("Television", "Televizyon");
        kelimeler.put("Camera", "Kamera");
        kelimeler.put("Headphones", "Kulaklık");
        kelimeler.put("Speaker", "Hoparlör");
        kelimeler.put("Internet", "İnternet");
        kelimeler.put("Website", "Web sitesi");
        kelimeler.put("Social Media", "Sosyal Medya");
        kelimeler.put("Email", "E-posta");
        kelimeler.put("Message", "Mesaj");
        kelimeler.put("Call", "Arama");
        kelimeler.put("Video Call", "Video arama");
        kelimeler.put("Chat", "Sohbet");
        kelimeler.put("Emoticon", "Emotikon");
        kelimeler.put("Emoji", "Emoji");
        kelimeler.put("Profile", "Profil");
        kelimeler.put("Username", "Kullanıcı adı");
        kelimeler.put("Password", "Parola");
        kelimeler.put("Security", "Güvenlik");
        kelimeler.put("Privacy", "Gizlilik");
        kelimeler.put("Settings", "Ayarlar");
        kelimeler.put("Notification", "Bildirim");
        kelimeler.put("App", "Uygulama");
        kelimeler.put("Download", "İndirme");
        kelimeler.put("Upload", "Yükleme");
        kelimeler.put("File", "Dosya");
        kelimeler.put("Folder", "Klasör");
        kelimeler.put("Document", "Belge");
        kelimeler.put("Presentation", "Sunum");
        kelimeler.put("Spreadsheet", "Elektronik tablo");
        kelimeler.put("Database", "Veritabanı");
        kelimeler.put("Programming", "Programlama");
        kelimeler.put("Code", "Kod");
        kelimeler.put("Developer", "Geliştirici");
        kelimeler.put("Bug", "Hata");
        kelimeler.put("Debugging", "Hata ayıklama");
        kelimeler.put("Version", "Sürüm");
        kelimeler.put("Update", "Güncelleme");
        kelimeler.put("Release", "Yayımlama");
        kelimeler.put("Open Source", "Açık kaynak");
        kelimeler.put("License", "Lisans");
        kelimeler.put("Community", "Topluluk");
        kelimeler.put("Collaboration", "İşbirliği");
        kelimeler.put("Project", "Proje");
        kelimeler.put("Deadline", "Son tarih");
        kelimeler.put("Meeting", "Toplantı");
        kelimeler.put("Team", "Ekip");
        kelimeler.put("Manager", "Yönetici");
        kelimeler.put("Colleague", "İş arkadaşı");
        kelimeler.put("Office", "Ofis");
        kelimeler.put("Remote", "Uzaktan");
        kelimeler.put("Work", "Çalışma");
        kelimeler.put("Job", "İş");
        kelimeler.put("Career", "Kariyer");
        kelimeler.put("Success", "Başarı");
        kelimeler.put("Failure", "Başarısızlık");
        kelimeler.put("Motivation", "Motivasyon");
        kelimeler.put("Goal", "Hedef");
        kelimeler.put("Productivity", "Üretkenlik");
        kelimeler.put("Efficiency", "Verimlilik");
        kelimeler.put("Quality", "Kalite");
        kelimeler.put("Customer", "Müşteri");
        kelimeler.put("Service", "Hizmet");
        kelimeler.put("Experience", "Deneyim");
        kelimeler.put("Satisfaction", "Memnuniyet");
        kelimeler.put("Feedback", "Geribildirim");
        kelimeler.put("Complaint", "Şikayet");
        kelimeler.put("Resolution", "Çözüm");
        kelimeler.put("Innovation", "Yenilik");
        kelimeler.put("Creativity", "Yaratıcılık");
        kelimeler.put("Imagination", "Hayal gücü");
        kelimeler.put("Inspiration", "İlham");
        kelimeler.put("Art", "Sanat");
        kelimeler.put("Music", "Müzik");
        kelimeler.put("Literature", "Edebiyat");
        kelimeler.put("Film", "Film");
        kelimeler.put("Theatre", "Tiyatro");
        kelimeler.put("Dance", "Dans");
        kelimeler.put("Visual Arts", "Görsel Sanatlar");
        kelimeler.put("Craft", "El sanatı");
        kelimeler.put("Design", "Tasarım");
        kelimeler.put("Fashion", "Moda");
        kelimeler.put("Architecture", "Mimarlık");
        kelimeler.put("Photography", "Fotoğrafçılık");
        kelimeler.put("Cuisine", "Mutfak");
        kelimeler.put("Culinary", "Mutfak sanatları");
        kelimeler.put("Food", "Yemek");
        kelimeler.put("Cooking", "Pişirme");
        kelimeler.put("Baking", "Fırınlama");
        kelimeler.put("Ingredient", "Malzeme");
        kelimeler.put("Recipe", "Tarif");
        kelimeler.put("Flavor", "Lezzet");
        kelimeler.put("Taste", "Tat");
        kelimeler.put("Spice", "Baharat");
        kelimeler.put("Herb", "Bitki");
        kelimeler.put("Beverage", "İçecek");
        kelimeler.put("Wine", "Şarap");
        kelimeler.put("Beer", "Bira");
        kelimeler.put("Coffee", "Kahve");
        kelimeler.put("Tea", "Çay");
        kelimeler.put("Cocktail", "Kokteyl");
        kelimeler.put("Juice", "Meyve suyu");
        kelimeler.put("Soft Drink", "Gazlı içecek");
        kelimeler.put("Water", "Su");
        kelimeler.put("Soda", "Soda");
        kelimeler.put("Health", "Sağlık");
        kelimeler.put("Wellness", "Sağlıklı yaşam");
        kelimeler.put("Fitness", "Fitness");
        kelimeler.put("Exercise", "Egzersiz");
        kelimeler.put("Nutrition", "Beslenme");
        kelimeler.put("Diet", "Diyet");
        kelimeler.put("Mental Health", "Mental sağlık");
        kelimeler.put("Stress", "Stres");
        kelimeler.put("Relaxation", "Rahatlama");
        kelimeler.put("Mindfulness", "Farkındalık");
        kelimeler.put("Social", "Sosyal");
        kelimeler.put("Relationship", "İlişki");
        kelimeler.put("Friendship", "Dostluk");
        kelimeler.put("Love", "Aşk");
        kelimeler.put("Marriage", "Evlilik");
        kelimeler.put("Family", "Aile");
        kelimeler.put("Parent", "Ebeveyn");
        kelimeler.put("Child", "Çocuk");
        kelimeler.put("Sibling", "Kardeş");
        kelimeler.put("Relative", "Akraba");
        kelimeler.put("Friend", "Arkadaş");
        kelimeler.put("Neighbour", "Komşu");
        kelimeler.put("Community", "Topluluk");
        kelimeler.put("City", "Şehir");
        kelimeler.put("Village", "Köy");
        kelimeler.put("Town", "Kasaba");
        kelimeler.put("Holiday", "Tatil");
        kelimeler.put("Vacation", "İzin");
        kelimeler.put("Adventure", "Macera");
        kelimeler.put("Explore", "Keşfetmek");
        kelimeler.put("Tourism", "Turizm");
        kelimeler.put("Destination", "Hedef");
        kelimeler.put("Journey", "Yolculuk");
        kelimeler.put("Traveler", "Seyyah");
        kelimeler.put("Guide", "Rehber");
        kelimeler.put("Map", "Harita");
        kelimeler.put("Compass", "Pusula");
        kelimeler.put("Backpack", "Sırt çantası");
        kelimeler.put("Hotel", "Otel");
        kelimeler.put("Reservation", "Rezervasyon");
        kelimeler.put("Check-in", "Giriş yapmak");
        kelimeler.put("Check-out", "Çıkış yapmak");
        kelimeler.put("Room", "Oda");
        kelimeler.put("Suite", "Süit");
        kelimeler.put("Hostel", "Pansiyon");
        kelimeler.put("Camping", "Kamp yapma");
        kelimeler.put("Beach", "Plaj");
        kelimeler.put("Mountain", "Dağ");
        kelimeler.put("Forest", "Orman");
        kelimeler.put("Lake", "Göl");
        kelimeler.put("River", "Nehir");
        kelimeler.put("Island", "Ada");
        kelimeler.put("Ocean", "Okyanuz");
        kelimeler.put("Sunset", "Günbatımı");
        kelimeler.put("Sunrise", "Gündoğumu");
        kelimeler.put("Star", "Yıldız");
        kelimeler.put("Galaxy", "Galaksi");
        kelimeler.put("Universe", "Evren");
        kelimeler.put("Astronomy", "Astronomi");
        kelimeler.put("Telescope", "Teleskop");
        kelimeler.put("Planet", "Gezegen");
        kelimeler.put("Satellite", "Uydu");
        kelimeler.put("Constellation", "Takımyıldız");
        kelimeler.put("Science", "Bilim");
        kelimeler.put("Technology", "Teknoloji");
        kelimeler.put("Innovation", "İnovasyon");
        kelimeler.put("Research", "Araştırma");
        kelimeler.put("Discovery", "Keşif");
        kelimeler.put("Experiment", "Deney");
        kelimeler.put("Hypothesis", "Hipotez");
        kelimeler.put("Theory", "Teori");
        kelimeler.put("Law", "Yasa");
        kelimeler.put("Scientist", "Bilim adamı");
        kelimeler.put("Laboratory", "Laboratuvar");
        kelimeler.put("Chemistry", "Kimya");
        kelimeler.put("Physics", "Fizik");
        kelimeler.put("Biology", "Biyoloji");
        kelimeler.put("Mathematics", "Matematik");
        kelimeler.put("Geology", "Jeoloji");
        kelimeler.put("Environment", "Çevre");
        kelimeler.put("Ecology", "Ekoloji");
        kelimeler.put("Sustainability", "Sürdürülebilirlik");
        kelimeler.put("Conservation", "Koruma");
        kelimeler.put("Biodiversity", "Biyolojik çeşitlilik");
        kelimeler.put("Natural Resources", "Doğal kaynaklar");
        kelimeler.put("Climate Change", "İklim Değişikliği");
        kelimeler.put("Weather", "Hava Durumu");
        kelimeler.put("Climate", "İklim");
        kelimeler.put("Temperature", "Sıcaklık");
        kelimeler.put("Rainfall", "Yağış");
        kelimeler.put("Snowfall", "Kar yağışı");
        kelimeler.put("Wind Speed", "Rüzgar hızı");
        kelimeler.put("Hurricane", "Kasırga");
        kelimeler.put("Earthquake", "Deprem");
        kelimeler.put("Tornado", "Tornado");
        kelimeler.put("Flood", "Sel");
        kelimeler.put("Fire", "Yangın");
        kelimeler.put("Emergency", "Acil durum");
        kelimeler.put("First Aid", "İlk yardım");
        kelimeler.put("Safety", "Güvenlik");
        kelimeler.put("Prevention", "Önleme");
        kelimeler.put("Awareness", "Farkındalık");
        kelimeler.put("Community", "Topluluk");
        kelimeler.put("Volunteer", "Gönüllü");
        kelimeler.put("Donation", "Bağış");
        kelimeler.put("Charity", "Hayır kurumu");
        kelimeler.put("Philanthropy", "Felsefe");
        kelimeler.put("Culture", "Kültür");
        kelimeler.put("Tradition", "Gelenek");
        kelimeler.put("Custom", "Adet");
        kelimeler.put("Language", "Dil");
        kelimeler.put("Communication", "İletişim");
        kelimeler.put("Media", "Medya");
        kelimeler.put("Newspaper", "Gazete");
        kelimeler.put("Magazine", "Dergi");
        kelimeler.put("Radio", "Radyo");
        kelimeler.put("Television", "Televizyon");
        kelimeler.put("Internet", "İnternet");
        kelimeler.put("Social Media", "Sosyal Medya");
        kelimeler.put("Journalism", "Gazetecilik");
        kelimeler.put("Reporter", "Muhabir");
        kelimeler.put("Editor", "Editör");
        kelimeler.put("News", "Haberler");
        kelimeler.put("Headline", "Manşet");
        kelimeler.put("Interview", "Röportaj");
        kelimeler.put("Article", "Makale");
        kelimeler.put("Opinion", "Görüş");
        kelimeler.put("Analysis", "Analiz");
        kelimeler.put("Entertainment", "Eğlence");
        kelimeler.put("Music", "Müzik");
        kelimeler.put("Film", "Film");
        kelimeler.put("Theatre", "Tiyatro");
        kelimeler.put("Art", "Sanat");
        kelimeler.put("Literature", "Edebiyat");
        kelimeler.put("Performance", "Performans");
        kelimeler.put("Concert", "Konser");
        kelimeler.put("Festival", "Festival");
        kelimeler.put("Celebration", "Kutlama");
        kelimeler.put("Party", "Parti");
        kelimeler.put("Dance", "Dans");
        kelimeler.put("Fashion", "Moda");
        kelimeler.put("Design", "Tasarım");
        kelimeler.put("Style", "Stil");
        kelimeler.put("Trend", "Trend");
        kelimeler.put("Beauty", "Güzellik");
        kelimeler.put("Health", "Sağlık");
        kelimeler.put("Wellness", "Sağlıklı yaşam");
        kelimeler.put("Fitness", "Fitness");
        kelimeler.put("Exercise", "Egzersiz");
        kelimeler.put("Nutrition", "Beslenme");
        kelimeler.put("Diet", "Diyet");
        kelimeler.put("Mental Health", "Mental sağlık");
        kelimeler.put("Stress", "Stres");
        kelimeler.put("Relaxation", "Rahatlama");
        kelimeler.put("Mindfulness", "Farkındalık");
        kelimeler.put("Hobby", "Hobi");
        kelimeler.put("Art", "Sanat");
        kelimeler.put("Craft", "El sanatı");
        kelimeler.put("Music", "Müzik");
        kelimeler.put("Reading", "Okuma");
        kelimeler.put("Writing", "Yazma");
        kelimeler.put("Photography", "Fotoğrafçılık");
        kelimeler.put("Travel", "Seyahat");
        kelimeler.put("Gardening", "Bahçe işleri");
        kelimeler.put("Cooking", "Pişirme");
        kelimeler.put("Sports", "Spor");
        kelimeler.put("Football", "Futbol");
        kelimeler.put("Basketball", "Basketbol");
        kelimeler.put("Tennis", "Tenis");
        kelimeler.put("Swimming", "Yüzme");
        kelimeler.put("Cycling", "Bisiklet");
        kelimeler.put("Running", "Koşu");
        kelimeler.put("Nature", "Doğa");
        kelimeler.put("Environment", "Çevre");
        kelimeler.put("Climate", "İklim");
        kelimeler.put("Green", "Yeşil");
        kelimeler.put("Animal", "Hayvan");
        kelimeler.put("Plant", "Bitki");
        kelimeler.put("Tree", "Ağaç");
        kelimeler.put("Flower", "Çiçek");
        kelimeler.put("Bird", "Kuş");
        kelimeler.put("Insect", "Böcek");
        kelimeler.put("Fish", "Balık");
        kelimeler.put("Reptile", "Sürüngen");
        kelimeler.put("Amphibian", "Amfibi");
        kelimeler.put("Mammal", "Memeli");
        kelimeler.put("Human", "İnsan");
        kelimeler.put("Society", "Toplum");
        kelimeler.put("Culture", "Kültür");
        kelimeler.put("Tradition", "Gelenek");
        kelimeler.put("Custom", "Adet");
        kelimeler.put("Language", "Dil");
        kelimeler.put("Communication", "İletişim");
        kelimeler.put("Relationship", "İlişki");
        kelimeler.put("Friendship", "Dostluk");
        kelimeler.put("Love", "Aşk");
        kelimeler.put("Marriage", "Evlilik");
        kelimeler.put("Family", "Aile");
        kelimeler.put("Parent", "Ebeveyn");
        kelimeler.put("Child", "Çocuk");
        kelimeler.put("Sibling", "Kardeş");
        kelimeler.put("Relative", "Akraba");
        kelimeler.put("Friend", "Arkadaş");
        kelimeler.put("Neighbour", "Komşu");
        kelimeler.put("Community", "Topluluk");
        kelimeler.put("City", "Şehir");
        kelimeler.put("Village", "Köy");
        kelimeler.put("Town", "Kasaba");
        kelimeler.put("Building", "Bina");
        kelimeler.put("House", "Ev");
        kelimeler.put("Apartment", "Apartman");
        kelimeler.put("Room", "Oda");
        kelimeler.put("Furniture", "Mobilya");
        kelimeler.put("Bed", "Yatak");
        kelimeler.put("Sofa", "Kanepe");
        kelimeler.put("Table", "Masa");
        kelimeler.put("Chair", "Sandalye");
        kelimeler.put("Closet", "Dolap");
        kelimeler.put("Electronics", "Elektronik");
        kelimeler.put("Computer", "Bilgisayar");
        kelimeler.put("Laptop", "Dizüstü bilgisayar");
        kelimeler.put("Tablet", "Tablet");
        kelimeler.put("Smartphone", "Akıllı telefon");
        kelimeler.put("Television", "Televizyon");
        kelimeler.put("Camera", "Kamera");
        kelimeler.put("Headphones", "Kulaklık");
        kelimeler.put("Speaker", "Hoparlör");
        kelimeler.put("Internet", "İnternet");
        kelimeler.put("Website", "Web sitesi");
        kelimeler.put("Social Media", "Sosyal Medya");
        kelimeler.put("Email", "E-posta");
        kelimeler.put("Message", "Mesaj");
        kelimeler.put("Call", "Arama");
        kelimeler.put("Video Call", "Video arama");
        kelimeler.put("Chat", "Sohbet");
        kelimeler.put("Emoticon", "Emotikon");
        kelimeler.put("Emoji", "Emoji");
        kelimeler.put("Profile", "Profil");
        kelimeler.put("Username", "Kullanıcı adı");
        kelimeler.put("Password", "Parola");
        kelimeler.put("Security", "Güvenlik");
        kelimeler.put("Privacy", "Gizlilik");
        kelimeler.put("Settings", "Ayarlar");
        kelimeler.put("Notification", "Bildirim");
        kelimeler.put("App", "Uygulama");
        kelimeler.put("Download", "İndirme");
        kelimeler.put("Upload", "Yükleme");
        kelimeler.put("File", "Dosya");
        kelimeler.put("Folder", "Klasör");
        kelimeler.put("Document", "Belge");
        kelimeler.put("Presentation", "Sunum");
        kelimeler.put("Spreadsheet", "Elektronik tablo");
        kelimeler.put("Database", "Veritabanı");
        kelimeler.put("Programming", "Programlama");
        kelimeler.put("Code", "Kod");
        kelimeler.put("Developer", "Geliştirici");
        kelimeler.put("Bug", "Hata");
        kelimeler.put("Debugging", "Hata ayıklama");
        kelimeler.put("Version", "Sürüm");
        kelimeler.put("Update", "Güncelleme");
        kelimeler.put("Release", "Yayımlama");
        kelimeler.put("Open Source", "Açık kaynak");
        kelimeler.put("License", "Lisans");
        kelimeler.put("Community", "Topluluk");
        kelimeler.put("Collaboration", "İşbirliği");
        kelimeler.put("Project", "Proje");
        kelimeler.put("Deadline", "Son tarih");
        kelimeler.put("Meeting", "Toplantı");
        kelimeler.put("Team", "Ekip");
        kelimeler.put("Manager", "Yönetici");
        kelimeler.put("Colleague", "İş arkadaşı");
        kelimeler.put("Office", "Ofis");
        kelimeler.put("Remote", "Uzaktan");
        kelimeler.put("Work", "Çalışma");
        kelimeler.put("Job", "İş");
        kelimeler.put("Career", "Kariyer");
        kelimeler.put("Success", "Başarı");
        kelimeler.put("Failure", "Başarısızlık");
        kelimeler.put("Motivation", "Motivasyon");
        kelimeler.put("Goal", "Hedef");
        kelimeler.put("Productivity", "Üretkenlik");
        kelimeler.put("Efficiency", "Verimlilik");
        kelimeler.put("Quality", "Kalite");
        kelimeler.put("Customer", "Müşteri");
        kelimeler.put("Service", "Hizmet");
        kelimeler.put("Experience", "Deneyim");
        kelimeler.put("Satisfaction", "Memnuniyet");
        kelimeler.put("Feedback", "Geribildirim");
        kelimeler.put("Complaint", "Şikayet");
        kelimeler.put("Resolution", "Çözüm");
        kelimeler.put("Innovation", "Yenilik");
        kelimeler.put("Creativity", "Yaratıcılık");
        kelimeler.put("Imagination", "Hayal gücü");
        kelimeler.put("Inspiration", "İlham");
        kelimeler.put("Art", "Sanat");
        kelimeler.put("Music", "Müzik");
        kelimeler.put("Literature", "Edebiyat");
        kelimeler.put("Film", "Film");
        kelimeler.put("Theatre", "Tiyatro");
        kelimeler.put("Dance", "Dans");
        kelimeler.put("Visual Arts", "Görsel Sanatlar");
        kelimeler.put("Craft", "El sanatı");
        kelimeler.put("Design", "Tasarım");
        kelimeler.put("Fashion", "Moda");
        kelimeler.put("Architecture", "Mimarlık");
        kelimeler.put("Photography", "Fotoğrafçılık");
        kelimeler.put("Cuisine", "Mutfak");
        kelimeler.put("Culinary", "Mutfak sanatları");
        kelimeler.put("Food", "Yemek");
        kelimeler.put("Cooking", "Pişirme");
        kelimeler.put("Baking", "Fırınlama");
        kelimeler.put("Ingredient", "Malzeme");
        kelimeler.put("Recipe", "Tarif");
        kelimeler.put("Flavor", "Lezzet");
        kelimeler.put("Taste", "Tat");
        kelimeler.put("Spice", "Baharat");
        kelimeler.put("Herb", "Bitki");
        kelimeler.put("Beverage", "İçecek");
        kelimeler.put("Wine", "Şarap");
        kelimeler.put("Beer", "Bira");
        kelimeler.put("Coffee", "Kahve");
        kelimeler.put("Tea", "Çay");
        kelimeler.put("Cocktail", "Kokteyl");
        kelimeler.put("Juice", "Meyve suyu");
        kelimeler.put("Soft Drink", "Gazlı içecek");
        kelimeler.put("Water", "Su");
        kelimeler.put("Soda", "Soda");
        kelimeler.put("Health", "Sağlık");
        kelimeler.put("Wellness", "Sağlıklı yaşam");
        kelimeler.put("Fitness", "Fitness");
        kelimeler.put("Exercise", "Egzersiz");
        kelimeler.put("Nutrition", "Beslenme");
        kelimeler.put("Diet", "Diyet");
        kelimeler.put("Mental Health", "Mental sağlık");
        kelimeler.put("Stress", "Stres");
        kelimeler.put("Relaxation", "Rahatlama");
        kelimeler.put("Mindfulness", "Farkındalık");
        kelimeler.put("Country", "Ülke");
        kelimeler.put("Nation", "Ulke");
        kelimeler.put("Government", "Hükümet");
        kelimeler.put("Politics", "Politika");
        kelimeler.put("Democracy", "Demokrasi");
        kelimeler.put("Dictatorship", "Diktatörlük");
        kelimeler.put("Freedom", "Özgürlük");
        kelimeler.put("Equality", "Eşitlik");
        kelimeler.put("Justice", "Adalet");
        kelimeler.put("Law", "Hukuk");
        kelimeler.put("Crime", "Suç");
        kelimeler.put("Police", "Polis");
        kelimeler.put("Justice System", "Adalet sistemi");
        kelimeler.put("Human Rights", "İnsan hakları");
        kelimeler.put("Peace", "Barış");
        kelimeler.put("War", "Savaş");
        kelimeler.put("Conflict", "Çatışma");
        kelimeler.put("Military", "Askeri");
        kelimeler.put("Weapon", "Silah");
        kelimeler.put("Security", "Güvenlik");
        kelimeler.put("Terrorism", "Terörizm");
        kelimeler.put("Refugee", "Mülteci");
        kelimeler.put("Immigration", "Göç");
        kelimeler.put("Population", "Nüfus");
        kelimeler.put("Demography", "Demografi");
        kelimeler.put("Economics", "Ekonomi");
        kelimeler.put("Market", "Pazar");
        kelimeler.put("Trade", "Ticaret");
        kelimeler.put("Globalization", "Küreselleşme");
        kelimeler.put("Business", "İş");
        kelimeler.put("Entrepreneur", "Girişimci");
        kelimeler.put("Startup", "Girişim");
        kelimeler.put("Innovation", "İnovasyon");
        kelimeler.put("Technology", "Teknoloji");
        kelimeler.put("Digital", "Dijital");
        kelimeler.put("Social Media", "Sosyal Medya");
        kelimeler.put("Internet", "İnternet");
        kelimeler.put("Cybersecurity", "Siber güvenlik");
        kelimeler.put("Data", "Veri");
        kelimeler.put("Algorithm", "Algoritma");
        kelimeler.put("Artificial Intelligence", "Yapay Zeka");
        kelimeler.put("Virtual Reality", "Sanal Gerçeklik");
        kelimeler.put("Augmented Reality", "Artırılmış Gerçeklik");
        kelimeler.put("Robotics", "Robotik");
        kelimeler.put("Energy", "Enerji");
        kelimeler.put("Renewable", "Yenilenebilir");
        kelimeler.put("Sustainability", "Sürdürülebilirlik");
        kelimeler.put("Climate Change", "İklim Değişikliği");
        kelimeler.put("Environment", "Çevre");
        kelimeler.put("Ecology", "Ekoloji");
        kelimeler.put("Conservation", "Koruma");
        kelimeler.put("Biodiversity", "Biyolojik çeşitlilik");
        kelimeler.put("Natural Resources", "Doğal kaynaklar");
        kelimeler.put("Weather", "Hava Durumu");
        kelimeler.put("Climate", "İklim");
        kelimeler.put("Temperature", "Sıcaklık");
        kelimeler.put("Rainfall", "Yağış");
        kelimeler.put("Snowfall", "Kar yağışı");
        kelimeler.put("Wind Speed", "Rüzgar hızı");
        kelimeler.put("Healthcare", "Sağlık hizmetleri");
        kelimeler.put("Hospital", "Hastane");
        kelimeler.put("Doctor", "Doktor");
        kelimeler.put("Nurse", "Hemşire");
        kelimeler.put("Patient", "Hasta");
        kelimeler.put("Medicine", "İlaç");
        kelimeler.put("Treatment", "Tedavi");
        kelimeler.put("Vaccine", "Aşı");
        kelimeler.put("Disease", "Hastalık");
        kelimeler.put("Epidemic", "Salgın");
        kelimeler.put("Pandemic", "Pandemi");
        kelimeler.put("Wellness", "Sağlıklı yaşam");
        kelimeler.put("Fitness", "Fitness");
        kelimeler.put("Exercise", "Egzersiz");
        kelimeler.put("Nutrition", "Beslenme");
        kelimeler.put("Diet", "Diyet");
        kelimeler.put("Mental Health", "Mental sağlık");
        kelimeler.put("Stress", "Stres");
        kelimeler.put("Relaxation", "Rahatlama");
        kelimeler.put("Mindfulness", "Farkındalık");
        kelimeler.put("Social", "Sosyal");
        kelimeler.put("Relationship", "İlişki");
        kelimeler.put("Friendship", "Dostluk");
        kelimeler.put("Love", "Aşk");
        kelimeler.put("Marriage", "Evlilik");
        kelimeler.put("Family", "Aile");
        kelimeler.put("Parent", "Ebeveyn");
        kelimeler.put("Child", "Çocuk");
        kelimeler.put("Sibling", "Kardeş");
        kelimeler.put("Relative", "Akraba");
        kelimeler.put("Friend", "Arkadaş");
        kelimeler.put("Neighbour", "Komşu");
        kelimeler.put("Community", "Topluluk");
        kelimeler.put("City", "Şehir");
        kelimeler.put("Village", "Köy");
        kelimeler.put("Town", "Kasaba");
        kelimeler.put("Building", "Bina");
        kelimeler.put("House", "Ev");
        kelimeler.put("Apartment", "Apartman");
        kelimeler.put("Room", "Oda");
        kelimeler.put("Furniture", "Mobilya");
        kelimeler.put("Bed", "Yatak");
        kelimeler.put("Sofa", "Kanepe");
        kelimeler.put("Table", "Masa");
        kelimeler.put("Chair", "Sandalye");
        kelimeler.put("Closet", "Dolap");
        kelimeler.put("Electronics", "Elektronik");
        kelimeler.put("Computer", "Bilgisayar");
        kelimeler.put("Laptop", "Dizüstü bilgisayar");
        kelimeler.put("Tablet", "Tablet");
        kelimeler.put("Smartphone", "Akıllı telefon");
        kelimeler.put("Television", "Televizyon");
        kelimeler.put("Camera", "Kamera");
        kelimeler.put("Headphones", "Kulaklık");
        kelimeler.put("Speaker", "Hoparlör");
        kelimeler.put("Internet", "İnternet");
        kelimeler.put("Website", "Web sitesi");
        kelimeler.put("Social Media", "Sosyal Medya");
        kelimeler.put("Email", "E-posta");
        kelimeler.put("Message", "Mesaj");
        kelimeler.put("Call", "Arama");
        kelimeler.put("Video Call", "Video arama");
        kelimeler.put("Chat", "Sohbet");
        kelimeler.put("Emoticon", "Emotikon");
        kelimeler.put("Emoji", "Emoji");
        kelimeler.put("Profile", "Profil");
        kelimeler.put("Username", "Kullanıcı adı");
        kelimeler.put("Password", "Parola");
        kelimeler.put("Security", "Güvenlik");
        kelimeler.put("Privacy", "Gizlilik");
        kelimeler.put("Settings", "Ayarlar");
        kelimeler.put("Notification", "Bildirim");
        kelimeler.put("App", "Uygulama");
        kelimeler.put("Download", "İndirme");
        kelimeler.put("Upload", "Yükleme");
        kelimeler.put("File", "Dosya");
        kelimeler.put("Folder", "Klasör");
        kelimeler.put("Document", "Belge");
        kelimeler.put("Presentation", "Sunum");
        kelimeler.put("Spreadsheet", "Elektronik tablo");
        kelimeler.put("Database", "Veritabanı");
        kelimeler.put("Programming", "Programlama");
        kelimeler.put("Code", "Kod");
        kelimeler.put("Developer", "Geliştirici");
        kelimeler.put("Bug", "Hata");
        kelimeler.put("Debugging", "Hata ayıklama");
        kelimeler.put("Version", "Sürüm");
        kelimeler.put("Update", "Güncelleme");
        kelimeler.put("Release", "Yayımlama");
        kelimeler.put("Open Source", "Açık kaynak");
        kelimeler.put("License", "Lisans");
        kelimeler.put("Community", "Topluluk");
        kelimeler.put("Collaboration", "İşbirliği");
        kelimeler.put("Project", "Proje");
        kelimeler.put("Deadline", "Son tarih");
        kelimeler.put("Meeting", "Toplantı");
        kelimeler.put("Team", "Ekip");
        kelimeler.put("Manager", "Yönetici");
        kelimeler.put("Colleague", "İş arkadaşı");
        kelimeler.put("Office", "Ofis");
        kelimeler.put("Remote", "Uzaktan");
        kelimeler.put("Work", "Çalışma");
        kelimeler.put("Job", "İş");
        kelimeler.put("Career", "Kariyer");
        kelimeler.put("Success", "Başarı");
        kelimeler.put("Failure", "Başarısızlık");
        kelimeler.put("Motivation", "Motivasyon");
        kelimeler.put("Goal", "Hedef");
        kelimeler.put("Productivity", "Üretkenlik");
        kelimeler.put("Efficiency", "Verimlilik");
        kelimeler.put("Quality", "Kalite");
        kelimeler.put("Customer", "Müşteri");
        kelimeler.put("Service", "Hizmet");
        kelimeler.put("Experience", "Deneyim");
        kelimeler.put("Satisfaction", "Memnuniyet");
        kelimeler.put("Feedback", "Geribildirim");
        kelimeler.put("Complaint", "Şikayet");
        kelimeler.put("Resolution", "Çözüm");
        kelimeler.put("Innovation", "Yenilik");
        kelimeler.put("Creativity", "Yaratıcılık");
        kelimeler.put("Imagination", "Hayal gücü");
        kelimeler.put("Inspiration", "İlham");
        kelimeler.put("Art", "Sanat");
        kelimeler.put("Music", "Müzik");
        kelimeler.put("Literature", "Edebiyat");
        kelimeler.put("Film", "Film");
        kelimeler.put("Theatre", "Tiyatro");
        kelimeler.put("Dance", "Dans");
        kelimeler.put("Visual Arts", "Görsel Sanatlar");
        kelimeler.put("Craft", "El sanatı");
        kelimeler.put("Design", "Tasarım");
        kelimeler.put("Fashion", "Moda");
        kelimeler.put("Architecture", "Mimarlık");
        kelimeler.put("Photography", "Fotoğrafçılık");
        kelimeler.put("Cuisine", "Mutfak");
        kelimeler.put("Culinary", "Mutfak sanatları");
        kelimeler.put("Food", "Yemek");
        kelimeler.put("Cooking", "Pişirme");
        kelimeler.put("Baking", "Fırınlama");
        kelimeler.put("Ingredient", "Malzeme");
        kelimeler.put("Recipe", "Tarif");
        kelimeler.put("Flavor", "Lezzet");
        kelimeler.put("Taste", "Tat");
        kelimeler.put("Spice", "Baharat");
        kelimeler.put("Herb", "Bitki");
        kelimeler.put("Beverage", "İçecek");
        kelimeler.put("Wine", "Şarap");
        kelimeler.put("Beer", "Bira");
        kelimeler.put("Coffee", "Kahve");
        kelimeler.put("Tea", "Çay");
        kelimeler.put("Cocktail", "Kokteyl");
        kelimeler.put("Juice", "Meyve suyu");
        kelimeler.put("Soft Drink", "Gazlı içecek");
        kelimeler.put("Water", "Su");
        kelimeler.put("Soda", "Soda");
        kelimeler.put("Health", "Sağlık");
        kelimeler.put("Wellness", "Sağlıklı yaşam");
        kelimeler.put("Fitness", "Fitness");
        kelimeler.put("Exercise", "Egzersiz");
        kelimeler.put("Nutrition", "Beslenme");
        kelimeler.put("Diet", "Diyet");
        kelimeler.put("Mental Health", "Mental sağlık");
        kelimeler.put("Stress", "Stres");
        kelimeler.put("Relaxation", "Rahatlama");
        kelimeler.put("Mindfulness", "Farkındalık");
        kelimeler.put("Hobby", "Hobi");
        kelimeler.put("Art", "Sanat");
        kelimeler.put("Craft", "El sanatı");
        kelimeler.put("Music", "Müzik");
        kelimeler.put("Reading", "Okuma");
        kelimeler.put("Writing", "Yazma");
        kelimeler.put("Photography", "Fotoğrafçılık");
        kelimeler.put("Travel", "Seyahat");
        kelimeler.put("Gardening", "Bahçe işleri");
        kelimeler.put("Cooking", "Pişirme");
        kelimeler.put("Sports", "Spor");
        kelimeler.put("Football", "Futbol");
        kelimeler.put("Basketball", "Basketbol");
        kelimeler.put("Tennis", "Tenis");
        kelimeler.put("Swimming", "Yüzme");
        kelimeler.put("Cycling", "Bisiklet");
        kelimeler.put("Running", "Koşu");
        kelimeler.put("Nature", "Doğa");
        kelimeler.put("Environment", "Çevre");
        kelimeler.put("Climate", "İklim");
        kelimeler.put("Green", "Yeşil");
        kelimeler.put("Animal", "Hayvan");
        kelimeler.put("Plant", "Bitki");
        kelimeler.put("Tree", "Ağaç");
        kelimeler.put("Flower", "Çiçek");
        kelimeler.put("Bird", "Kuş");
        kelimeler.put("Insect", "Böcek");
        kelimeler.put("Fish", "Balık");
        kelimeler.put("Reptile", "Sürüngen");
        kelimeler.put("Amphibian", "Amfibi");
        kelimeler.put("Mammal", "Memeli");
        kelimeler.put("Human", "İnsan");
        kelimeler.put("Society", "Toplum");
        kelimeler.put("Culture", "Kültür");
        kelimeler.put("Tradition", "Gelenek");
        kelimeler.put("Custom", "Adet");
        kelimeler.put("Language", "Dil");
        kelimeler.put("Communication", "İletişim");
        kelimeler.put("Relationship", "İlişki");
        kelimeler.put("Friendship", "Dostluk");
        kelimeler.put("Love", "Aşk");
        kelimeler.put("Marriage", "Evlilik");
        kelimeler.put("Family", "Aile");
        kelimeler.put("Parent", "Ebeveyn");
        kelimeler.put("Child", "Çocuk");
        kelimeler.put("Sibling", "Kardeş");
        kelimeler.put("Relative", "Akraba");
        kelimeler.put("Friend", "Arkadaş");
        kelimeler.put("Neighbour", "Komşu");
        kelimeler.put("Community", "Topluluk");
        kelimeler.put("City", "Şehir");
        kelimeler.put("Village", "Köy");
        kelimeler.put("Town", "Kasaba");
        kelimeler.put("Building", "Bina");
        kelimeler.put("House", "Ev");
        kelimeler.put("Apartment", "Apartman");
        kelimeler.put("Room", "Oda");
        kelimeler.put("Furniture", "Mobilya");
        kelimeler.put("Bed", "Yatak");
        kelimeler.put("Sofa", "Kanepe");
        kelimeler.put("Table", "Masa");
        kelimeler.put("Chair", "Sandalye");
        kelimeler.put("Closet", "Dolap");
        kelimeler.put("Electronics", "Elektronik");
        kelimeler.put("Computer", "Bilgisayar");
        kelimeler.put("Laptop", "Dizüstü bilgisayar");
        kelimeler.put("Tablet", "Tablet");
        kelimeler.put("Smartphone", "Akıllı telefon");
        kelimeler.put("Television", "Televizyon");
        kelimeler.put("Camera", "Kamera");
        kelimeler.put("Headphones", "Kulaklık");
        kelimeler.put("Speaker", "Hoparlör");
        kelimeler.put("Internet", "İnternet");
        kelimeler.put("Website", "Web sitesi");
        kelimeler.put("Social Media", "Sosyal Medya");
        kelimeler.put("Email", "E-posta");
        kelimeler.put("Message", "Mesaj");
        kelimeler.put("Call", "Arama");
        kelimeler.put("Video Call", "Video arama");
        kelimeler.put("Chat", "Sohbet");
        kelimeler.put("Emoticon", "Emotikon");
        kelimeler.put("Emoji", "Emoji");
        kelimeler.put("Profile", "Profil");
        kelimeler.put("Username", "Kullanıcı adı");
        kelimeler.put("Password", "Parola");
        kelimeler.put("Security", "Güvenlik");
        kelimeler.put("Privacy", "Gizlilik");
        kelimeler.put("Settings", "Ayarlar");
        kelimeler.put("Notification", "Bildirim");
        kelimeler.put("App", "Uygulama");
        kelimeler.put("Download", "İndirme");
        kelimeler.put("Upload", "Yükleme");
        kelimeler.put("File", "Dosya");
        kelimeler.put("Folder", "Klasör");
        kelimeler.put("Document", "Belge");
        kelimeler.put("Presentation", "Sunum");
        kelimeler.put("Spreadsheet", "Elektronik tablo");
        kelimeler.put("Database", "Veritabanı");
        kelimeler.put("Programming", "Programlama");
        kelimeler.put("Code", "Kod");
        kelimeler.put("Developer", "Geliştirici");
        kelimeler.put("Bug", "Hata");
        kelimeler.put("Debugging", "Hata ayıklama");
        kelimeler.put("Version", "Sürüm");
        kelimeler.put("Update", "Güncelleme");
        kelimeler.put("Release", "Yayımlama");
        kelimeler.put("Open Source", "Açık kaynak");
        kelimeler.put("License", "Lisans");
        kelimeler.put("Community", "Topluluk");
        kelimeler.put("Collaboration", "İşbirliği");
        kelimeler.put("Project", "Proje");
        kelimeler.put("Deadline", "Son tarih");
        kelimeler.put("Meeting", "Toplantı");
        kelimeler.put("Team", "Ekip");
        kelimeler.put("Manager", "Yönetici");
        kelimeler.put("Colleague", "İş arkadaşı");
        kelimeler.put("Office", "Ofis");
        kelimeler.put("Remote", "Uzaktan");
        kelimeler.put("Work", "Çalışma");
        kelimeler.put("Job", "İş");
        kelimeler.put("Career", "Kariyer");
        kelimeler.put("Success", "Başarı");
        kelimeler.put("Failure", "Başarısızlık");
        kelimeler.put("Motivation", "Motivasyon");
        kelimeler.put("Goal", "Hedef");
        kelimeler.put("Productivity", "Üretkenlik");
        kelimeler.put("Efficiency", "Verimlilik");
        kelimeler.put("Quality", "Kalite");
        kelimeler.put("Customer", "Müşteri");
        kelimeler.put("Service", "Hizmet");
        kelimeler.put("Experience", "Deneyim");
        kelimeler.put("Satisfaction", "Memnuniyet");
        kelimeler.put("Feedback", "Geribildirim");
        kelimeler.put("Complaint", "Şikayet");
        kelimeler.put("Resolution", "Çözüm");
        kelimeler.put("Innovation", "Yenilik");
        kelimeler.put("Creativity", "Yaratıcılık");
        kelimeler.put("Imagination", "Hayal gücü");
        kelimeler.put("Inspiration", "İlham");
        kelimeler.put("Art", "Sanat");
        kelimeler.put("Music", "Müzik");
        kelimeler.put("Literature", "Edebiyat");
        kelimeler.put("Film", "Film");
        kelimeler.put("Theatre", "Tiyatro");
        kelimeler.put("Dance", "Dans");
        kelimeler.put("Visual Arts", "Görsel Sanatlar");
        kelimeler.put("Craft", "El sanatı");
        kelimeler.put("Design", "Tasarım");
        kelimeler.put("Fashion", "Moda");
        kelimeler.put("Architecture", "Mimarlık");
        kelimeler.put("Photography", "Fotoğrafçılık");
        kelimeler.put("Cuisine", "Mutfak");
        kelimeler.put("Culinary", "Mutfak sanatları");
        kelimeler.put("Food", "Yemek");
        kelimeler.put("Cooking", "Pişirme");
        kelimeler.put("Baking", "Fırınlama");
        kelimeler.put("Ingredient", "Malzeme");
        kelimeler.put("Recipe", "Tarif");
        kelimeler.put("Flavor", "Lezzet");
        kelimeler.put("Taste", "Tat");
        kelimeler.put("Spice", "Baharat");
        kelimeler.put("Herb", "Bitki");
        kelimeler.put("Beverage", "İçecek");
        kelimeler.put("Wine", "Şarap");
        kelimeler.put("Beer", "Bira");
        kelimeler.put("Coffee", "Kahve");
        kelimeler.put("Tea", "Çay");
        kelimeler.put("Cocktail", "Kokteyl");
        kelimeler.put("Juice", "Meyve suyu");
        kelimeler.put("Soft Drink", "Gazlı içecek");
        kelimeler.put("Water", "Su");
        kelimeler.put("Soda", "Soda");
        kelimeler.put("Health", "Sağlık");
        kelimeler.put("Wellness", "Sağlıklı yaşam");
        kelimeler.put("Fitness", "Fitness");
        kelimeler.put("Exercise", "Egzersiz");
        kelimeler.put("Nutrition", "Beslenme");
        kelimeler.put("Diet", "Diyet");
        kelimeler.put("Mental Health", "Mental sağlık");
        kelimeler.put("Stress", "Stres");
        kelimeler.put("Relaxation", "Rahatlama");
        kelimeler.put("Friendship", "Dostluk");
        kelimeler.put("Garden", "Bahçe");
        kelimeler.put("Rain", "Yağmur");
        kelimeler.put("Coffee", "Kahve");
        kelimeler.put("Tea", "Çay");
        kelimeler.put("Mountain", "Dağ");
        kelimeler.put("Beach", "Plaj");
        kelimeler.put("Forest", "Orman");
        kelimeler.put("Flower", "Çiçek");
        kelimeler.put("Music", "Müzik");
        kelimeler.put("Dance", "Dans");
        kelimeler.put("Art", "Sanat");
        kelimeler.put("Science", "Bilim");
        kelimeler.put("History", "Tarih");
        kelimeler.put("Mathematics", "Matematik");
        kelimeler.put("Science", "Bilim");
        kelimeler.put("History", "Tarih");
        kelimeler.put("Mathematics", "Matematik");
        kelimeler.put("Rainbow", "Gökkuşağı");
        kelimeler.put("Sunny", "Güneşli");
        kelimeler.put("Cloudy", "Bulutlu");
        kelimeler.put("Wind", "Rüzgar");
        kelimeler.put("Snow", "Kar");
        kelimeler.put("Ice", "Buz");
        kelimeler.put("Fire", "Ateş");
        kelimeler.put("Earth", "Dünya");
        kelimeler.put("Air", "Hava");
        kelimeler.put("Water", "Su");
        kelimeler.put("Fire", "Ateş");
        kelimeler.put("Earth", "Dünya");
        kelimeler.put("Air", "Hava");
        kelimeler.put("Water", "Su");
        kelimeler.put("Food", "Yemek");
        kelimeler.put("Vegetable", "Sebze");
        kelimeler.put("Fruit", "Meyve");
        kelimeler.put("Chocolate", "Çikolata");
        kelimeler.put("Breakfast", "Kahvaltı");
        kelimeler.put("Lunch", "Öğle yemeği");
        kelimeler.put("Dinner", "Akşam yemeği");
        kelimeler.put("Snack", "Atıştırma");
        kelimeler.put("Cooking", "Pişirme");
        kelimeler.put("Baking", "Fırınlama");
        kelimeler.put("Eating", "Yeme");
        kelimeler.put("Sleep", "Uyku");
        kelimeler.put("Dream", "Rüya");
        kelimeler.put("Night", "Gece");
        kelimeler.put("Day", "Gün");
        kelimeler.put("Morning", "Sabah");
        kelimeler.put("Afternoon", "Öğleden sonra");
        kelimeler.put("Evening", "Akşam");
        kelimeler.put("Time", "Zaman");
        kelimeler.put("Clock", "Saat");
        kelimeler.put("Watch", "Saat (kol saati)");
        kelimeler.put("Hour", "Saat (zaman birimi)");
        kelimeler.put("Minute", "Dakika");
        kelimeler.put("Second", "Saniye");
        kelimeler.put("Year", "Yıl");
        kelimeler.put("Month", "Ay");
        kelimeler.put("Week", "Hafta");
        kelimeler.put("Day", "Gün");
        kelimeler.put("Yesterday", "Dün");
        kelimeler.put("Today", "Bugün");
        kelimeler.put("Tomorrow", "Yarın");
        kelimeler.put("Holiday", "Tatil");
        kelimeler.put("Vacation", "Tatil");
        kelimeler.put("Travel", "Seyahat");
        kelimeler.put("Adventure", "Macera");
        kelimeler.put("Explore", "Keşfetmek");
        kelimeler.put("Map", "Harita");
        kelimeler.put("Guide", "Rehber");
        kelimeler.put("Tourist", "Turist");
        kelimeler.put("Hotel", "Otel");
        kelimeler.put("Room", "Oda");
        kelimeler.put("Reservation", "Rezervasyon");
        kelimeler.put("Ticket", "Bilet");
        kelimeler.put("Passport", "Pasaport");
        kelimeler.put("Airport", "Havalimanı");
        kelimeler.put("Train", "Tren");
        kelimeler.put("Bus", "Otobüs");
        kelimeler.put("Car", "Araba");
        kelimeler.put("Bicycle", "Bisiklet");
        kelimeler.put("Ship", "Gemi");
        kelimeler.put("Plane", "Uçak");
        kelimeler.put("Space", "Uzay");
        kelimeler.put("Planet", "Gezegen");
        kelimeler.put("Star", "Yıldız");
        kelimeler.put("Galaxy", "Galaksi");
        kelimeler.put("Sun", "Güneş");
        kelimeler.put("Moon", "Ay");
        kelimeler.put("Earth", "Dünya");
        kelimeler.put("Mars", "Mars");
        kelimeler.put("Jupiter", "Jüpiter");
        kelimeler.put("Saturn", "Satürn");
        kelimeler.put("Uranus", "Uranüs");
        kelimeler.put("Neptune", "Neptün");
        kelimeler.put("Mercury", "Merkür");
        kelimeler.put("Venus", "Venüs");
        kelimeler.put("Solar System", "Güneş Sistemi");
        kelimeler.put("Universe", "Evren");
        kelimeler.put("Science", "Bilim");
        kelimeler.put("Technology", "Teknoloji");
        kelimeler.put("Innovation", "Yenilik");
        kelimeler.put("Discovery", "Keşif");
        kelimeler.put("Experiment", "Deney");
        kelimeler.put("Laboratory", "Laboratuvar");
        kelimeler.put("Scientist", "Bilim Adamı");
        kelimeler.put("Research", "Araştırma");
        kelimeler.put("Study", "Çalışma");
        kelimeler.put("Knowledge", "Bilgi");
        kelimeler.put("Education", "Eğitim");
        kelimeler.put("School", "Okul");
        kelimeler.put("Teacher", "Öğretmen");
        kelimeler.put("Student", "Öğrenci");
        kelimeler.put("Classroom", "Sınıf");
        kelimeler.put("Lesson", "Ders");
        kelimeler.put("Homework", "Ev ödevi");
        kelimeler.put("Exam", "Sınav");
        kelimeler.put("Grade", "Not");
        kelimeler.put("Pass", "Geçmek");
        kelimeler.put("Fail", "Başarısız olmak");
        kelimeler.put("Success", "Başarı");
        kelimeler.put("Failure", "Başarısızlık");
        kelimeler.put("Achievement", "Başarı");
        kelimeler.put("Goal", "Hedef");
        kelimeler.put("Dream", "Rüya");
        kelimeler.put("Ambition", "Hırs");
        kelimeler.put("Career", "Kariyer");
        kelimeler.put("Job", "İş");
        kelimeler.put("Work", "Çalışma");
        kelimeler.put("Office", "Ofis");
        kelimeler.put("Colleague", "İş arkadaşı");
        kelimeler.put("Boss", "Patron");
        kelimeler.put("Meeting", "Toplantı");
        kelimeler.put("Presentation", "Sunum");
        kelimeler.put("Project", "Proje");
        kelimeler.put("Deadline", "Son tarih");
        kelimeler.put("Salary", "Maaş");
        kelimeler.put("Income", "Gelir");
        kelimeler.put("Expense", "Gider");
        kelimeler.put("Budget", "Bütçe");
        kelimeler.put("Savings", "Tasarruf");
        kelimeler.put("Investment", "Yatırım");
        kelimeler.put("Economy", "Ekonomi");
        kelimeler.put("Market", "Pazar");
        kelimeler.put("Product", "Ürün");
        kelimeler.put("Consumer", "Tüketici");
        kelimeler.put("Price", "Fiyat");
        kelimeler.put("Sale", "Satış");
        kelimeler.put("Purchase", "Satın alma");
        kelimeler.put("Shopping", "Alışveriş");
        kelimeler.put("Fashion", "Moda");
        kelimeler.put("Style", "Stil");
        kelimeler.put("Trend", "Trend");
        kelimeler.put("Clothing", "Giysi");
        kelimeler.put("Accessories", "Aksesuar");
        kelimeler.put("Shoes", "Ayakkabı");
        kelimeler.put("Bag", "Çanta");
        kelimeler.put("Jewelry", "Mücevher");
        kelimeler.put("Health", "Sağlık");
        kelimeler.put("Wellness", "Sağlıklı yaşam");
        kelimeler.put("Fitness", "Fitness");
        kelimeler.put("Exercise", "Egzersiz");
        kelimeler.put("Nutrition", "Beslenme");
        kelimeler.put("Diet", "Diyet");
        kelimeler.put("Sleep", "Uyku");
        kelimeler.put("Mental Health", "Mental sağlık");
        kelimeler.put("Stress", "Stres");
        kelimeler.put("Relaxation", "Rahatlama");
        kelimeler.put("Mindfulness", "Farkındalık");
        kelimeler.put("Hobby", "Hobi");
        kelimeler.put("Art", "Sanat");
        kelimeler.put("Craft", "El sanatı");
        kelimeler.put("Music", "Müzik");
        kelimeler.put("Reading", "Okuma");
        kelimeler.put("Writing", "Yazma");
        kelimeler.put("Photography", "Fotoğrafçılık");
        kelimeler.put("Travel", "Seyahat");
        kelimeler.put("Gardening", "Bahçe işleri");
        kelimeler.put("Cooking", "Pişirme");
        kelimeler.put("Sports", "Spor");
        kelimeler.put("Football", "Futbol");
        kelimeler.put("Basketball", "Basketbol");
        kelimeler.put("Tennis", "Tenis");
        kelimeler.put("Swimming", "Yüzme");
        kelimeler.put("Cycling", "Bisiklet");
        kelimeler.put("Running", "Koşu");
        kelimeler.put("Nature", "Doğa");
        kelimeler.put("Environment", "Çevre");
        kelimeler.put("Climate", "İklim");
        kelimeler.put("Green", "Yeşil");
        kelimeler.put("Animal", "Hayvan");
        kelimeler.put("Plant", "Bitki");
        kelimeler.put("Tree", "Ağaç");
        kelimeler.put("Flower", "Çiçek");
        kelimeler.put("Bird", "Kuş");
        kelimeler.put("Insect", "Böcek");
        kelimeler.put("Fish", "Balık");
        kelimeler.put("Reptile", "Sürüngen");
        kelimeler.put("Amphibian", "Amfibi");
        kelimeler.put("Mammal", "Memeli");
        kelimeler.put("Human", "İnsan");
        kelimeler.put("Society", "Toplum");
        kelimeler.put("Happiness", "Mutluluk");
        kelimeler.put("Sadness", "Üzüntü");
        kelimeler.put("Anger", "Öfke");
        kelimeler.put("Love", "Aşk");
        kelimeler.put("Peace", "Barış");
        kelimeler.put("Hello", "Merhaba");
        kelimeler.put("Name", "İsim");
        kelimeler.put("Town", "Kasaba");
        kelimeler.put("Goodbye", "Hoşça kal");
        kelimeler.put("Friend", "Arkadaş");
        kelimeler.put("Family", "Aile");
        kelimeler.put("Dog", "Köpek");
        kelimeler.put("Cat", "Kedi");
        kelimeler.put("Sun", "Güneş");
        kelimeler.put("Moon", "Ay");
        kelimeler.put("Star", "Yıldız");
        kelimeler.put("Sky", "Gökyüzü");
        kelimeler.put("Ocean", "Okyanus");
        kelimeler.put("Mountain", "Dağ");
        kelimeler.put("River", "Nehir");
        kelimeler.put("Computer", "Bilgisayar");
        kelimeler.put("Programming", "Programlama");
        kelimeler.put("Language", "Dil");
        kelimeler.put("Code", "Kod");
        kelimeler.put("Developer", "Geliştirici");
        kelimeler.put("Project", "Proje");
        kelimeler.put("Keyboard", "Klavye");
        kelimeler.put("Mouse", "Fare");
        kelimeler.put("Screen", "Ekran");
        kelimeler.put("Internet", "İnternet");
        kelimeler.put("Website", "Web sitesi");
        kelimeler.put("Mobile", "Mobil");
        kelimeler.put("Application", "Uygulama");
        kelimeler.put("Hope", "Umud");
        kelimeler.put("Fear", "Korku");
        kelimeler.put("Joy", "Sevinç");
        kelimeler.put("Surprise", "Şaşkınlık");
        kelimeler.put("Excitement", "Heyecan");
        kelimeler.put("Book", "Kitap");
        kelimeler.put("Pen", "Kalem");
        kelimeler.put("Paper", "Kağıt");
        kelimeler.put("Desk", "Masa");
        kelimeler.put("Chair", "Sandalye");
        kelimeler.put("Lamp", "Lamba");
        kelimeler.put("Window", "Pencere");
        kelimeler.put("Door", "Kapı");
        kelimeler.put("Clock", "Saat");
        kelimeler.put("Table", "Masa");
        kelimeler.put("Culture", "Kültür");
        kelimeler.put("Tradition", "Gelenek");
        kelimeler.put("Custom", "Adet");
        kelimeler.put("Language", "Dil");
        kelimeler.put("Communication", "İletişim");
        kelimeler.put("Relationship", "İlişki");
        kelimeler.put("Friendship", "Dostluk");
        kelimeler.put("Love", "Aşk");
        kelimeler.put("Marriage", "Evlilik");
        kelimeler.put("Family", "Aile");
        kelimeler.put("Parent", "Ebeveyn");
        kelimeler.put("Child", "Çocuk");
        kelimeler.put("Sibling", "Kardeş");
        kelimeler.put("Relative", "Akraba");
        kelimeler.put("Friend", "Arkadaş");
        kelimeler.put("Neighbour", "Komşu");
        kelimeler.put("Community", "Topluluk");
        kelimeler.put("City", "Şehir");
        kelimeler.put("Village", "Köy");
        kelimeler.put("Town", "Kasaba");
        kelimeler.put("Mindfulness", "Farkındalık");
        kelimeler.put("Social", "Sosyal");
        kelimeler.put("Relationship", "İlişki");
        kelimeler.put("Friendship", "Dostluk");
        kelimeler.put("Love", "Aşk");
        kelimeler.put("Marriage", "Evlilik");
        kelimeler.put("Family", "Aile");
        kelimeler.put("Parent", "Ebeveyn");
        kelimeler.put("Child", "Çocuk");
        kelimeler.put("Sibling", "Kardeş");
        kelimeler.put("Relative", "Akraba");
        kelimeler.put("Friend", "Arkadaş");
        kelimeler.put("Neighbour", "Komşu");
        kelimeler.put("Community", "Topluluk");
        kelimeler.put("City", "Şehir");
        kelimeler.put("Village", "Köy");
        kelimeler.put("Town", "Kasaba");
        kelimeler.put("Social", "Sosyal");
        kelimeler.put("Relationship", "İlişki");
        kelimeler.put("Friendship", "Dostluk");
        kelimeler.put("Love", "Aşk");
        kelimeler.put("Marriage", "Evlilik");
        kelimeler.put("Family", "Aile");
        kelimeler.put("Parent", "Ebeveyn");
        kelimeler.put("Child", "Çocuk");
        kelimeler.put("Sibling", "Kardeş");
        kelimeler.put("Relative", "Akraba");
        kelimeler.put("Friend", "Arkadaş");
        kelimeler.put("Neighbour", "Komşu");
        kelimeler.put("Community", "Topluluk");
        kelimeler.put("City", "Şehir");
        kelimeler.put("Village", "Köy");
        kelimeler.put("Town", "Kasaba");
        kelimeler.put("Holiday", "Tatil");
        kelimeler.put("Compass", "Pusula");
        kelimeler.put("Backpack", "Sırt çantası");
        kelimeler.put("Hotel", "Otel");
        kelimeler.put("Reservation", "Rezervasyon");
        kelimeler.put("Check-in", "Giriş yapmak");
        kelimeler.put("Check-out", "Çıkış yapmak");
        kelimeler.put("Room", "Oda");
        kelimeler.put("Suite", "Süit");
        kelimeler.put("Adventure", "Macera");
        kelimeler.put("Explore", "Keşfetmek");
        kelimeler.put("Tourism", "Turizm");
        kelimeler.put("Destination", "Hedef");
        kelimeler.put("Journey", "Yolculuk");
        kelimeler.put("Traveler", "Seyyah");
        kelimeler.put("Guide", "Rehber");
        kelimeler.put("Hostel", "Pansiyon");
        kelimeler.put("Camping", "Kamp yapma");
        kelimeler.put("Beach", "Plaj");
        kelimeler.put("Mountain", "Dağ");
        kelimeler.put("Forest", "Orman");
        kelimeler.put("Lake", "Göl");
        kelimeler.put("River", "Nehir");
        kelimeler.put("Island", "Ada");
        kelimeler.put("Ocean", "Okyanuz");
        kelimeler.put("Sunset", "Günbatımı");
        kelimeler.put("Art", "Sanat");
        kelimeler.put("Literature", "Edebiyat");
        kelimeler.put("Performance", "Performans");
        kelimeler.put("Concert", "Konser");
        kelimeler.put("Festival", "Festival");
        kelimeler.put("Celebration", "Kutlama");
        kelimeler.put("Party", "Parti");
        kelimeler.put("Dance", "Dans");
        kelimeler.put("Fashion", "Moda");
        kelimeler.put("Design", "Tasarım");
        kelimeler.put("Style", "Stil");
        kelimeler.put("Trend", "Trend");
    }

}